### ISSUE TITLE
I tried multiple times according to the process, but only showed 'ok' and then had no response

### ISSUE THREAD

**Issue by haohaoya12** [Kramar1337/Deadlock-AHK-External#1]

**Comment by SAZER02** [comment]
Открывать через блокнот файлы и искать
Dk\ДедКок-КрамКвадраты.ahk
boxTeam = 1
boxEnemy = 1
SleepCpu = 1 	; рекомендую 20. для идеальной плавности 0, но жрет много CPU 5% в моем случае
boneDBGmode = 0 	;показывать индексы костей для настройки ДедКок-КрамАимбот.ahk

Dk\ДедКок-КрамАимбот.ahk
key_aim := "V"
sensitivity := 0.5  	; 0.05	Чувствительность движения
tolerance := 1       	; 2 	Допустимое расстояние до цели для остановки движения
captureRange := 150  	; 100 пикселей
SleepCpu = 1 			; 0 для идеальной плавности но жрет много CPU 5% в моем случае
BoneMode = 1 			; 1 - кости из базы, 0 - выбрать самую верхнюю кость(промахи, например, поднятые руки выше уровня головы)
headOrneck = 1 			; 1 - приоритет на голову из базы, 0 - приоритет на шею из базы

Dk\ДедКок-КрамРадар.ahk
radarBoxEnable = 0 	; Рекомендую 0 чтобы не мешала рамка
radarShowName = 1 	; Рекомендую 1 чтобы знать кто гангает
radarShowTeam = 0 	; Рекомендую 0 чтобы не мешало

Just modify this setting in Notepad and run it.    and run "1337offsetsUpdate.ahk" If it shows "OK", you can start playing the game.

**Comment by haohaoya12** [comment]
![2024-09-17_145521](https://github.com/user-attachments/assets/2abcbfb8-770f-4f75-8b5c-c7367a2de489)
According to your method, a red circle appeared, but the function did not load. Pressing 'v' did not produce any response, and reloading resulted in an image error.

**Comment by SAZER02** [comment]
qq2817369604

**Comment by Kramar1337** [comment]
use an empty account that you don't mind losing
install autohotkey
download repository
use windowed frameless mode in the game
run
"DedKok-KramAimbot.ahk"
"DedKok-KramKvadraty.ahk"
"DedKok-KramRadar.ahk"
enter sandbox mode and check if everything works.
if nothing happens, close the scripts with the "End" key or in the tray menu.
run "data\1337offsetsUpdate.ahk"
the script will update the offsets (the game must be running for the script to find the addresses).
run
"DedKok-KramAimbot.ahk"
"DedKok-KramKvadraty.ahk"
"DedKok-KramRadar.ahk"
the settings are stored in the files themselves, you need to open the files themselves through notepad.
if nothing helps, the scripts are probably outdated, wait until I update the repository.
