### ISSUE TITLE
Аим на души.

### ISSUE THREAD

**Issue by setikus** [Kramar1337/Deadlock-AHK-External#12]
Аим на души иногда просто не наводится на них, на какие то наводится, на какие то нет. Пытался понять в чем проблема, так и не смог, надеюсь автор подскажет что не так. Заранее спасибо !

**Comment by setikus** [comment]
https://jumpshare.com/s/tpRsU28R5Z9d0RYZ1MW7

**Comment by setikus** [comment]
Я не знаю с чем это связано, но оно наводится на души с крипов очень плохо, на тестовые идеально.

**Comment by Kramar1337** [comment]
чета там габен в обнове намудрил, я переделал, стало лучше но не идеально.
