### ISSUE TITLE
Это даже не иссуе а предложение вопрос

### ISSUE THREAD

**Issue by daybeforethesuicide** [Kramar1337/Deadlock-AHK-External#13]
Нет в планах добавить фиксацию цели при захвате аимом? Частенько стреляешь в цель на лоу хп а аим переводится на фулл хп цель которая ближе по дистанции к тебе, или сделать чтобы аим ставил в приоритет цель с меньшим количеством хп? А еще проверку чтобы через стены на другой конец карты не наводилось.. или через препятствия. Я понимаю что ты делаешь это на собственном энтузиазме, поэтому просто спрашиваю)

**Comment by Kramar1337** [comment]
захват есть, у тебя старая версия. проверку видимости не умею делать, если попадется исходник на с++ то изучу и добавлю.
