### ISSUE TITLE
After the program update, it seems that a new problem has arisen: The "Lock Souls" function does not work properly when the Sandbox is enabled and entered into the main game. It does not work at the beginning, and then it sometimes does not work later on.

### ISSUE THREAD

**Issue by haohaoya12** [Kramar1337/Deadlock-AHK-External#14]

**Comment by setikus** [comment]
Вот об этом и была моя последняя тема кстати )

**Comment by Kramar1337** [comment]
на обработку списка сущностей уходит какое-то время и с душами мобов есть проблемы.
кароч, переделал, но если в момент рождения души не было синхронизации то аим не сработает(первая пачка крипов будет просрана получается)
