### ISSUE TITLE
Как насчет того, что бы добавить возможность отключать запоминание цели на аиме. 

### ISSUE THREAD

**Issue by setikus** [Kramar1337/Deadlock-AHK-External#17]
Запоминание цели отличная функция, но для большей легитности было бы не плохо иметь возможность ее отключить. Пример: Чувак делает деш в меня пролетает насквозь, я идеально веду за ним и делаю 180, это гига палевно)
Спасибо за понимание !

**Comment by serge24680** [comment]
У меня на боковой кнопке мыши АИМ и 1.8 стоит в настройках Аима. Почти фулл легит и аимлю только когда нужно )

**Comment by Kramar1337** [comment]
добавил настройку в конфиге
; При запоминании цели, если цель вышла из зоны захвата, больше *1.5 от диапазона, то терять цель - 1. Не терять цель никогда - 0
LegitCaptureRange=1
