### ISSUE TITLE
how to use pz

### ISSUE THREAD

**Issue by SAZER02** [Kramar1337/Deadlock-AHK-External#2]
In the previous version without icon.ico, it was able to run and use normally, but now this latest version runs without any effect in the game

**Comment by SAZER02** [comment]
I can use    thanks

**Comment by Kramar1337** [comment]
use an empty account that you don't mind losing
install autohotkey
download repository
use windowed frameless mode in the game
run
"DedKok-KramAimbot.ahk"
"DedKok-KramKvadraty.ahk"
"DedKok-KramRadar.ahk"
enter sandbox mode and check if everything works.
if nothing happens, close the scripts with the "End" key or in the tray menu.
run "data\1337offsetsUpdate.ahk"
the script will update the offsets (the game must be running for the script to find the addresses).
run
"DedKok-KramAimbot.ahk"
"DedKok-KramKvadraty.ahk"
"DedKok-KramRadar.ahk"
the settings are stored in the files themselves, you need to open the files themselves through notepad.
if nothing helps, the scripts are probably outdated, wait until I update the repository.

**Comment by SAZER02** [comment]
you are so nice, thank you.
