### ISSUE TITLE
бро вернись D;

### ISSUE THREAD

**Issue by l3rm37** [Kramar1337/Deadlock-AHK-External#20]

**Comment by serge24680** [comment]
Запусти DBG. Нажми ок ок ок. Откроется документ и напишет скопировано в буфе. В документа удали все где начинается Статик и вставь то что скопировалось в буфер. Сохрани и все ворк 
![JjREmkB](https://github.com/user-attachments/assets/922839a2-5332-4b5b-972f-b78ca26bacd5)

**Comment by SmallWhite-aw** [comment]
Thank you I can work
