### ISSUE TITLE
Compared to the new DGB code, it seems that the offset has not been updated, but it has become invalid

### ISSUE THREAD

**Issue by rookieis** [Kramar1337/Deadlock-AHK-External#25]
Compared to the new DGB code, it seems that the offset has not been updated, but it has become invalid

**Comment by Kramar1337** [comment]
я больше не играю в deadlock.
читайте внимательно описание:
Открыть: https://a2x.github.io/cs2-analyzer/
Отдать ему "steamapps\common\Deadlock\game\citadel\bin\win64\client.dll"
Открыть вкладку "Classes"
Искать оффсеты

; C_BasePlayerPawn
static m_pCameraServices = 0xd58

m_pCameraServices - имя оффсета
0xd58 - адрес
C_BasePlayerPawn - это имя раздела

**Comment by Kramar1337** [comment]
I don't play deadlock anymore.
read the description carefully:
Open: https://a2x.github.io/cs2-analyzer/
Give it "steamapps\common\Deadlock\game\citadel\bin\win64\client.dll"
Open the "Classes" tab
Search for offsets

; C_BasePlayerPawn
static m_pCameraServices = 0xd58

m_pCameraServices is the offset name
0xd58 is the address
C_BasePlayerPawn is the section name

**Comment by Kramar1337** [comment]
sometimes offsets can be taken here
https://github.com/Loara228/deadlock-esp/blob/master/src/external/offsets/mod.rs

**Comment by Kramar1337** [comment]
also update
dwGameEntitySystem_highestEntityIndex

Run "1337Flex.ahk" => "DBG"
Open client.dll, automatically opens the folder with the file if the game is open or find the path yourself
For example steamapps\common\Deadlock\game\citadel\bin\win64\client.dll
Click "CS2-Analyzer", the site will open, give it "client.dll"
On the site, tab "Offsets"
find dwGameEntitySystem_highestEntityIndex
Run "1337Flex.ahk" => "DBG"
Tab "Debugging" => "OffDump.ahk"
update dwGameEntitySystem_highestEntityIndex

**Comment by y0shih** [comment]
checked everything like u said but it still doesn't work i don't think it is an offset bug hope u can take a look at it
