### ISSUE TITLE
updated offsets and everything but still not work

### ISSUE THREAD

**Issue by y0shih** [Kramar1337/Deadlock-AHK-External#26]
class offsets
{
; C_BasePlayerPawn
static m_pCameraServices = 0xD50
; CPlayer_CameraServices
static m_vecPunchAngle = 0x40
; CEntityInstance
static m_pEntity = 0x10
static m_designerName = 0x20
; CGameSceneNode
static m_vecAbsOrigin = 0xD0
static m_bDormant = 0xEF
; C_BaseEntity
static m_pGameSceneNode = 0x330
static m_iTeamNum = 0x3F3
static m_vecVelocity = 0x410
; CBasePlayerController
static m_hPawn = 0x634
; CSkeletonInstance
static m_modelState = 0x170
; CModelState
static m_hModel = 0x0D0
; CCitadelPlayerController
static m_PlayerDataGlobal = 0x830
; PlayerDataGlobal_t
static m_iHealth = 0x354
static m_iHealthMax = 0x10
static m_bAlive = 0x60
static m_nHeroID = 0x14
static m_iGoldNetWorth = 0x20
static m_iAPNetWorth = 0x24
static m_bUltimateTrained = 0x68
static m_flUltimateCooldownEnd = 0x70
; C_GameRules
static m_nTotalPausedTicks = 0x30
; C_CitadelPlayerPawn
static m_angLockedEyeAngles = 0x1004

updated offsets 
dwGameEntitySystem_highestEntityIndex = 0x2100 still stay the same 

Hope you can take a look at it

**Comment by Kramar1337** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/fcedbc54-63c4-4197-942b-211927addead)

**Comment by Kramar1337** [comment]
https://github.com/Loara228/deadlock-esp/blob/master/src/external/offsets/mod.rs

**Comment by Kramar1337** [comment]
aimbot is broken. everything will work except aimbot

**Comment by y0shih** [comment]
> aimbot is broken. everything will work except aimbot

Can u tell me more what make it not to work so i can look it into myself easier? ty tho
