### ISSUE TITLE
Клиент обновляется так быстро, а, более 10 часов, снова не работает, пожалуйста, обновите!

### ISSUE THREAD

**Issue by haohaoya12** [Kramar1337/Deadlock-AHK-External#3]

**Comment by setikus** [comment]
Первый раз запустилось ок, но не работало. Обновил офсеты автоматом, не обновились (был в игре), тут тоже ок, обновил вручную. Теперь при запуске выдает данную базу 
![image](https://github.com/user-attachments/assets/ce8843e5-6bdf-433e-b88f-8b5357b2122e)

**Comment by haohaoya12** [comment]
Можно получить доступ к методу обновления смещения, который он предлагает для обновления. У меня получилось.

**Comment by haohaoya12** [comment]
It would be nice to update the channel a little faster

**Comment by Kramar1337** [comment]
the script must be run as administrator
I updated the offsets
