### ISSUE TITLE
 Up Сценарий показывает, что после обновления ok, offsrts показывает только один элемент dwEntityList, как я могу попытаться обновить его в режиме администратора 

### ISSUE THREAD

**Issue by haohaoya12** [Kramar1337/Deadlock-AHK-External#4]

**Comment by haohaoya12** [comment]
Как мне запустить скрипт в режиме администратора.Или как заставить его выйти полностью.

**Comment by haohaoya12** [comment]
Все они используются для перевода и вывода, и могут быть некоторые неточные выражения

**Comment by Kramar1337** [comment]
удалить все
скачать репозиторий
распаковать
запустить игру
запустить "1337offsetsUpdate.ahk" правый клик мыши по файлу "запустить от имени администратора"
запустить любой из скриптов

пс. я обновил оффсеты
