### ISSUE TITLE
Проблема с хилбаром в esp.

### ISSUE THREAD

**Issue by daybeforethesuicide** [Kramar1337/Deadlock-AHK-External#7]
![Безымянный](https://github.com/user-attachments/assets/edce6b0d-60de-40d6-9408-b1b9aeee45c4)
Хил бар учитывает щиты от барьеров и т.п за здоровье, либо он не правильно высчитывает базовое минимальное хп, отсюда и такой прикол, это и в катке и в песке, после смерти персонажа его минимально отображаемое здоровье становится корректным и баг исчезает пока он не купит или не улучшит щиты до больших значений и все опять по новой. Оффсеты все обновлены, проблема в чём-то другом.
началось после выхода последнего патча с миражом и обновлением скриптов. До этого проблем не было.

**Comment by Kramar1337** [comment]
полоска рисует хп от максимального(m_iMaxHealth), дополнительное хп не учитывает.
переделал но не тестил.
